safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - autolink
    - no_intra_emphasis
    - smart
    - strikethrough
    - superscript

permalink: /jfdi/:title.html
